#!/bin/bash

echo;
echo -en '°'"\r"; sleep .1;
echo -en '°º'"\r"; sleep .1;
echo -en '°º¤'"\r"; sleep .1;
echo -en '°º¤ø'"\r"; sleep .1;
echo -en '°º¤ø,'"\r"; sleep .1;
echo -en '°º¤ø,¸'"\r"; sleep .1;
echo -en '°º¤ø,¸¸'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,ø'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,ø,'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,ø,¸'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,ø,¸,'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,ø,¸,¸'"\r"; sleep .1;
echo -en '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,ø,¸,¸¸'"\r"; sleep .1;
echo     '°º¤ø,¸¸,ø¤º°º¤ø,¸,ø¤º¤ø,¸,ø,¸,¸¸¸¸'; sleep .1;

