#!/bin/sh
#
# Copy docs to usb drive:

DISK="MC16GB_HFS"

echo ""
echo "WARNING:  This will copy the the Documents sparseimage"
echo "and the general DevonThink databases"
echo "To the *USB drive* ${DISK} from the Mac."
echo ""
printf "Are you sure you want to do this? (y/n) "
read x

case "$x" in
y|yes|Y|YES|Yes)
echo rsync -acvzE --exclude ".DS_Store" --delete ${HOME}/Documents/_Docs_work.sparsebundle/ /Volumes/${DISK}/_Docs_work.sparsebundle
#rsync -acvzE --exclude ".DS_Store" --delete ${HOME}/Documents/_Docs_work.sparsebundle/ /Volumes/${DISK}/_Docs_work.sparsebundle
echo
echo rsync -acvzE --exclude ".DS_Store" --delete ${HOME}/Documents/DevonThink/ /Volumes/${DISK}/DevonThink
#rsync -acvzE --exclude ".DS_Store" --delete ${HOME}/Documents/DevonThink/ /Volumes/${DISK}/DevonThink
  ;;

n|no|N|NO|No)
  echo "No action taken"
  ;;

*)
  echo "Usage: n = no, do not copy.  y = yes, copy files"
  ;;

esac

exit 0


