#!/bin/bash -x
#
#exec emacsclient --alternate-editor="" -t "$@"

if [ `command -v emacsclient` >/dev/null 2>&1 ]; then
    exec emacsclient -t "$@"
elif [ `command -v zile` >/dev/null 2>&1 ]; then
    exec zile "$@"
else
    exec vi "$@"
fi
