#!/bin/bash

EMACS_SOCKET="${HOME}/.emacs.d/tmp/server"

# Prefer emacs with alternalte mg
# -s: socket   -n: don't wait   -a: alternate editor
if [ `command -v emacsclient` >/dev/null 2>&1 ]; then
    exec emacsclient -s "${EMACS_SOCKET}" -n -a mg "$@"
elif [ `command -v ng` >/dev/null 2>&1 ]; then
    exec mg "$@"
else
    exec vi "$@"
fi
