#!/bin/bash

EMACS_SOCKET="${HOME}/.emacs.d/tmp/server"

# Prefer emacs with alternalte zile
# -s: socket   -n: don't wait   -a: alternate editor
if [ `command -v emacsclient` >/dev/null 2>&1 ]; then
    exec emacsclient -s "${EMACS_SOCKET}" -n -a zile "$@"
elif [ `command -v zile` >/dev/null 2>&1 ]; then
    exec zile "$@"
else
    exec vi "$@"
fi
