#!/bin/bash

if [[ -z $* ]]; then
	ls /Volumes | {
		while read x; do
			echo $x
		done
	} | sort
	# echo "`basename $0`: syntax error"
	exit 0
fi

if echo "$*" | grep -qv Volumes; then
	hdiutil eject "/Volumes/$*"
else
	hdiutil eject "$*"
fi
