#!/bin/bash

echo;
echo -en "( º_º）  ┬─┬   \r"; sleep .5;
echo -en " ( º_º） ┬─┬   \r"; sleep .5;
echo -en "  ( ºДº）┬─┬   \r"; sleep .5;
echo -en "  (╯'Д'）╯︵⊏   \r"; sleep .5;
echo -en "  (╯'□'）╯︵ ⊏  \r"; sleep .5;
echo     "  (╯°□°）╯︵ ┻━┻"; sleep .5;
