#!/bin/sh

# globpath
# (c) 2005 Kim Holburn <kim.holburn@nicta.com.au>
# released under the GPL v2 http://www.gnu.org/copyleft/gpl.html

# examples: globpath '*ping*'

SAVEIFS="$IFS"
IFS=":"
paths=( $PATH )
IFS="$SAVEIFS"

pings=( $(echo ${paths[@]/%/\/$1}) )

found=0
for i in ${pings[@]}; do
  if [ -e "$i" ]; then
    echo "$i"
    found=1
  fi 
done
if [ "$found" -eq 0 ]; then
  echo "nothing found"
fi
