#!/bin/bash

IP="10.1.246.11"

case ${1} in
    on)
        curl -PUT http://${IP}/on.php
    ;;
    off)
        curl -PUT http://${IP}/off.php
    ;;
    *)
        echo "Usage:  klaxon {on|off}"
    ;;
esac

