#!/bin/bash
#
# Touch a file in the Timesheets directory with Monday's date
# Run from Crontab each Monday
#
# 30 8 * * 1 ~/bin/monday

LOGDIR="${HOME}/org/DailyLogs/"

# Change to DailyLogs directory, if it doesn't exist create it
if [ -d ${LOGDIR} ]; then
    cd ${LOGDIR}
else
    mkdir ${LOGDIR}
    cd ${LOGDIR}
fi

/bin/date '+%Y%m%d--%b-%d-%Y' >.monday
