#!/bin/bash
### BEGIN INIT INFO
# Provides:          MountSharedFolders
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mount Shared Folders
# Description:       Enables mount of vmware shared folders to /mnt/hgfs
#                    in Linux
### END INIT INFO
cd /mnt

if [ ! -d "hgfs" ]; then
	mkdir hgfs
fi

mount -t vmhgfs .host:/ /mnt/hgfs
