#!/bin/bash


cat - <<"EOF"

    DECOMMISSIONED: http://slc2pxsql0201.menupages.seamless.com/  ssh 10.68.169.20

    DECOMMISSIONED: http://slc2pxsql0202.menupages.seamless.com/  ssh 10.68.169.21


    rdms-tomcat01.prod.chi2.take.out

    rdms-tomcat02.prod.chi2.take.out

    RDS Jump host: 10.172.40.55		Uses LDAP.  Pwd set 11/14/2018

    RDS Instance: prod-driverpayment-ro01.czqtd04byygm.us-east-1.rds.amazonaws.com

    chi2pdmenudb01.take.out ( I do have access )

    CERT servers
    chi2pdqimydb01    ssh 10.160.100.208	Real: 10.160.100.55

    chi2pdqimydb02    ssh 10.160.100.209	Real: 10.160.100.54


    packmule-db02.prod.chi2.take.out		  ssh 10.160.15.71

    packmule-db03.prod.chi2.take.out		  ssh 10.160.15.72


    managed-delivery-db01.prod.chi2.take.out	  ssh 10.160.15.120

    managed-delivery-db02.prod.chi2.take.out	  ssh 10.160.15.121


    mysql01.prod.chi2.take.out	ssh 10.160.15.41

    mysql02.prod.chi2.take.out	ssh 10.160.15.30

    mysql03.prod.chi2.take.out	ssh 10.160.15.31

    mysql04.prod.chi2.take.out	ssh 10.160.15.40

    mysql05.prod.chi2.take.out	ssh 10.160.15.50

    mysql06.prod.chi2.take.out	ssh 10.160.15.51

    mysql07.prod.chi2.take.out	ssh 10.160.15.52

    mysql08.prod.chi2.take.out	ssh 10.160.15.53

    mysql09.prod.chi2.take.out  ssh 10.160.15.54

    mysql10.prod.chi2.take.out  ssh 10.160.15.55


    Cassandra admin servers:

    cassandra-admin-1.prod.ghbeta.com

    cassandra-admin-1.preprod.ghbeta.com


    GFW:
    ----
    Dev: gh4w-logs-dev.crgldi3vgvak.us-west-2.rds.amazonaws.com

    Prod: gh4w-logs-prod-us-west-2b.crgldi3vgvak.us-west-2.rds.amazonaws.com


    Jump Servers:
    -------------
    ssh sshjump01.prod.chi2.take.out
    ssh sshjump02.prod.chi2.take.out


EOF
## end of script
