#!/bin/bash
#
# Run at beginning of week to rotate log files and email previous
# weeks to self and supervisor.
#
# 1999 - Gerald Sievers
# 20110108 - djackson, updated to clean up code and add error checking

LOGDIR="${HOME}/org/DailyLogs"

# Check if the +current link is actually a link or has mystically became
# the log file, if so exit with a warning
if [ -e ${LOGDIR}/+current -a ! -L ${LOGDIR}/+current ]; then
  echo "WARNING:  +current has become a regular file, check contents!  Exiting."
  exit 1
fi

if [ -d ${LOGDIR} ]; then
  cd ${LOGDIR}
else
  echo -e "Log Directory ${LOGDIR} doesn't exist.\n\tHave you run the monday script yet?"
  exit 1
fi

# for loading of "SMTP", "mailTo", "mailFrom" and "yourName" variables if it exists
if [ -f .config ]; then
   . ./.config
else
  SMTP=""
  mailTo=""
  mailFrom=""
  yourName="Anonymous Employee"
fi

newfile=$( < .monday ) \
    || exit 1

# If newfile already exists, print error and exit
if [ -f "${newfile}" ]; then
    echo -e "
$0: ERROR... $newfile already exists.
\tdoing nothing." >&2
    exit 1
fi

# Delete +current and +Last symlinks, ~ backup files
rm -f +* *~

# Create new empty daily log file template
##echo -e "#-*- mode: org -*-\n
##$yourName  [ Week beginning Monday ${newfile#*--} ]\n
##Monday\n\n  .\n
##Tuesday\n\n\n
##Wednesday\n\n\n
##Thursday\n\n\n
##Friday\n\n" >${newfile}

echo -e "#-*- mode: org; fill-column: 78 -*-
#+STARTUP: overview

$yourName  [ Week beginning Monday ${newfile#*--} ]\n
* Monday
\n.
\n10:30-11 Log into GH4W to keep account active
\n11-11:30 [Meeting] Douglas / Randy 1:1
#+begin_text conf
# This week

# Last week

#+end_text
\n* Tuesday
\n9-9:15 [Meeting] Weekly GHC check (with Tim and Ryan)
\n11:30-12 [Meeting] GTFO - Team Meeting (Naan, 19tl)
#+begin_text conf
# Notes / Agenda

# Done tasks

# Today / Working on / TODO
#+end_text

\n1-5 SRE Heads Down Time
\n* Wednesday
\n11:20-12:30 Spicey Chicken
\n* Thursday
\n1-5 SRE Heads Down Time
\n* Friday
\n9:30-10:30 [Meeting] SRE's Unite (Spanakopita 19th fl)
\n10:30-11 Run 'topgrade' to update mac apps
\n11:30-12:30 Learning Friday/Technology Lunch
\n12:30-1 [Meeting] Kill Chi2 Biweekly Sync
\n1-5 Learning Friday Time
\n2-3 [Meeting] Security Engineering Team: Weekly Status and Project Review
\n3-4 [Meeting] CHI SRE Team Retrospective
\n3:30-4 [Meeting] GTFO - Team Drinking
\n3-5 [Meeting] GrubPub Virtual Edition
\n* Notes:\n\n" >${newfile}

# Count the number of log files (whose name starts with 0-9)
set [0-9]*

# If there are more then one, email the previous weeks log to... ?
if [ $# -gt 1 ]
then
        # Create +Last symlink to last week's log
        eval "ln -s \"\${$(( $# - 1 ))}\" +Last"

        # If mailTo is set, email the contents of +Last
        # (using nailx from the heirloom project for its smtp support)
        if [ "${mailTo}" ]
        then
            nailx -s "$( awk '/ Week beginning /' +Last )" -Ssmtp=${SMTP} -SmailFrom=${mailFrom} ${mailTo} <+Last
        fi
fi

# Create new symlink for +current
ln -s ${newfile} +current
